CosmosDB/CosmoGAB/src/Models/Address.cs
namespace CosmoGab.Models
{
    using Newtonsoft.Json;

    public class Address
    {
        [JsonProperty(PropertyName = "addressLine")]
        public string AddressLine { get; set; }

        [JsonProperty(PropertyName = "zipCode")]
        public string ZipCode { get; set; }
        [JsonProperty(PropertyName = "country")]
        public string Country { get; set; }
    }
}

CosmosDB/CosmoGAB/src/Models/Contact.cs
namespace CosmoGab.Models
{
    using System;

    using Newtonsoft.Json;

    public class Contact // : IHaveEntityType
    {
        [JsonProperty(PropertyName = "contactType")]
        public ContactType ContactType { get; set; }

        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        [JsonProperty(PropertyName = "firstName")]
        public string Firstname { get; set; }

        [JsonProperty(PropertyName = "lastName")]
        public string Lastname { get; set; }

        [JsonProperty(PropertyName = "birthDate")]
        public DateTime BirthDate { get; set; }

        [JsonProperty(PropertyName = "address")]
        public Address Address { get; set; }

        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        //[JsonProperty(PropertyName = "entityType")]
        //public string EntityType => "Contact";
    }
}

CosmosDB/CosmoGAB/src/Models/ContactType.cs
namespace CosmoGab.Models
{
    public enum ContactType
    {
        Customer,
        Supplier
    }
}

CosmosDB/CosmoGAB/src/Models/IHaveEntityType.cs
//namespace CosmoGab.Models
//{
//    public interface IHaveEntityType
//    {
//        string EntityType { get; }
//    }
//}

CosmosDB/CosmoGAB/src/Models/Item.cs
namespace CosmoGab.Models
{
    using Newtonsoft.Json;

    public class Item // : IHaveEntityType
    {
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        [JsonProperty(PropertyName = "isComplete")]
        public bool Completed { get; set; }

        //[JsonProperty(PropertyName = "entityType")]
        //public string EntityType => "Item";
    }
}

CosmosDB/CosmoGAB/src/Controllers/ContactController.cs
namespace CosmoGab.Controllers
{
    using System;
    using System.Linq.Expressions;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using CosmoGab.Models;

    using FizzWare.NBuilder;
    using FizzWare.NBuilder.Generators;

    public class ContactController : Controller
    {
        private readonly IDocumentDBRepository<Contact> documentDbRepository;

        public ContactController(IDocumentDBRepository<Contact> documentDbRepository)
        {
            this.documentDbRepository = documentDbRepository;
        }

        public async Task<ActionResult> Index()
        {
            // Expression<Func<Contact, bool>> expression = x => x.EntityType == "Contact";
            var items = await this.documentDbRepository.GetItemsAsync();
            return this.View(items);
        }

        public async Task<ActionResult> AddRandom()
        {
            var items = Builder<Contact>.CreateListOfSize(5)
                .All().With(x => x.Id = Guid.NewGuid().ToString())
                .With(x => x.Firstname = GetRandom.FirstName())
                .With(x => x.Lastname = GetRandom.LastName())
                .With(x => x.Description = GetRandom.Phrase(10))
                .With(x => x.BirthDate = GetRandom.DateTime())
                .With(x => x.Address = Builder<Address>.CreateNew()
                               .With(y => y.Country = GetRandom.Usa.State())
                               .With(y => y.AddressLine = GetRandom.Phrase(20))
                               .With(y => y.ZipCode = GetRandom.Int(0, 99999).ToString())
                               .Build())
                .Build();

            foreach (var item in items)
            {
                await this.documentDbRepository.CreateItemAsync(item);
            }

            return this.RedirectToAction("Index");
        }

        public async Task<ActionResult> Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( Contact item)
        {
            if (this.ModelState.IsValid)
            {
                await this.documentDbRepository.CreateItemAsync(item);
                return this.RedirectToAction("Index");
            }

            return this.View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Contact item)
        {
            if (this.ModelState.IsValid)
            {
                await this.documentDbRepository.UpdateItemAsync(item.Id, item);
                return this.RedirectToAction("Index");
            }

            return this.View(item);
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Contact item = await this.documentDbRepository.GetItemAsync(id);
            if (item == null)
            {
                return this.HttpNotFound();
            }

            return this.View(item);
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            await this.documentDbRepository.DeleteItemAsync(id);
            return this.RedirectToAction("Index");
        }
    }
}

CosmosDB/CosmoGAB/src/Controllers/ItemController.cs
namespace CosmoGab.Controllers
{
    using System;
    using System.Linq.Expressions;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using CosmoGab.Models;

    using FizzWare.NBuilder;
    using FizzWare.NBuilder.Generators;

    public class ItemController : Controller
    {
        private readonly IDocumentDBRepository<Item> documentDbRepository;

        public ItemController(IDocumentDBRepository<Item> documentDbRepository)
        {
            this.documentDbRepository = documentDbRepository;
        }

        public async Task<ActionResult> Index()
        {
            // Expression<Func<Item, bool>> expression = x => x.EntityType == "Item";
            var items = await this.documentDbRepository.GetItemsAsync();
            return this.View(items);
        }

        public async Task<ActionResult> AddRandom()
        {
            var items = Builder<Item>.CreateListOfSize(5)
                .All()
                .With(x => x.Id = Guid.NewGuid().ToString())
                .With(x => x.Description = GetRandom.Phrase(10))
                .With(x => x.Name = GetRandom.String(10))
                .Build();
            foreach (var item in items)
            {
                await this.documentDbRepository.CreateItemAsync(item);
            }

            return this.RedirectToAction("Index");
        }

        public async Task<ActionResult> Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Item item)
        {
            if (this.ModelState.IsValid)
            {
                await this.documentDbRepository.CreateItemAsync(item);
                return this.RedirectToAction("Index");
            }

            return this.View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Item item)
        {
            if (this.ModelState.IsValid)
            {
                await this.documentDbRepository.UpdateItemAsync(item.Id, item);
                return this.RedirectToAction("Index");
            }

            return this.View(item);
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Item item = await this.documentDbRepository.GetItemAsync(id);
            if (item == null)
            {
                return this.HttpNotFound();
            }

            return this.View(item);
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            await this.documentDbRepository.DeleteItemAsync(id);
            return this.RedirectToAction("Index");
        }
    }
}

CosmosDB/CosmoGAB/src/Views/Contact/Create.cshtml
@model CosmoGab.Models.Contact

@{
    ViewBag.Title = "Create";
}
<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Contact</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Firstname, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Lastname, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BirthDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
        </div>
    </div>

        @Html.EditorFor(model => model.Address)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CosmosDB/CosmoGAB/src/Views/Contact/Edit.cshtml
@model CosmoGab.Models.Contact

@{
    ViewBag.Title = "Edit";
}
<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Contact</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
        </div>
    </div>

        @Html.EditorFor(model => model.Address)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CosmosDB/CosmoGAB/src/Views/Contact/Index.cshtml
@model IEnumerable<CosmoGab.Models.Contact>
@{
    ViewBag.Title = "List of Contacts";
    var i = 1;
}
<h2>List of Contacts</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Add random elements", "AddRandom", null, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <td></td>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            #@(i++)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Firstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address.AddressLine) - @Html.DisplayFor(modelItem => item.Address.Country) - @Html.DisplayFor(modelItem => item.Address.ZipCode)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
    }
</table>

CosmosDB/CosmoGAB/src/Views/Item/Create.cshtml
@model Item

@{
    ViewBag.Title = "Create";
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Completed, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Completed)
                    @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CosmosDB/CosmoGAB/src/Views/Item/Edit.cshtml
@model CosmoGab.Models.Item

@{
    ViewBag.Title = "Edit";
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Completed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Completed)
                    @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CosmosDB/CosmoGAB/src/Views/Item/Index.cshtml
@model IEnumerable<Item>
@{
    ViewBag.Title = "List of To-Do Items";
    var i = 1;
}
<h2>List of To-Do Items</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Add random elements", "AddRandom", null, new {@class= "btn btn-success" })
</p>
<table class="table">
    <tr>
        <td></td>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Completed)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                #@(i++)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Completed)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

CosmosDB/CosmoGAB/src/Views/Shared/EditorTemplates/Address.cshtml
@model Address

<div class="form-horizontal">
    <h4>Address</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.AddressLine, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressLine, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressLine, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZipCode, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Country, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

CosmosDB/CosmoGAB/src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CosmoGAB", "Index", "Item", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Item")">To-do items</a></li>
                    <li><a href="@Url.Action("Index", "Contact")">Contacts</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - To-Do App with Azure DocumentDB</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>